### ISSUE TITLE
Custom css (styles or classNames) to customize editor and toolbar

### ISSUE THREAD

**Issue by gh4m21** [ozanyurtsever/verbum#12]
**Is your feature request related to a problem? Please describe.**
I am about to give Verbum a try because It's easy to set up but I got one issue. This issue is I can't style the Toolbar as I want. For example, the height of the toolbar component is 32px but I want to change it to 50px so that will fit my components but Ican't

**Describe the solution you'd like**
I think you can add default styles and class names, and concatenate the styles props and classnames props so anyone can customize the toolbar and the editor.

**Comment by ozanyurtsever** [comment]
Hello @gh4m21,

Adding custom styling abilities to this project is definitely on the roadmap, however I wouldn't be able to work on it lately due to my busy schedule. During that time, I think you can override the original css classes to customize the styling.

[Here](https://github.com/ozanyurtsever/verbum/blob/master/src/EditorComposer.css) is where all of the styling of the entire editor. You can play around and tweak the editor as you wish for your own projects.

**Comment by gh4m21** [comment]
Hello @ozanyurtsever,

I am going to make a pull request soon to add those changes. Thanks for your response🙏🏾

**Comment by ozanyurtsever** [comment]
@gh4m21  Perfect, much appreciated.
